// moon.ts — Mirrored from Lucide (https://lucide.dev), ISC licensed.
// Auto-generated by tools/build-icons.ts — do not edit by hand.

/** Inner SVG content for the `moon` icon. Wrap with your own
 * `<svg viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"
 * stroke-linecap="round" stroke-linejoin="round" fill="none">` to
 * control size and colour. */
export const moon =
  '<path d="M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401" />';
