// move.ts — Mirrored from Lucide (https://lucide.dev), ISC licensed.
// Auto-generated by tools/build-icons.ts — do not edit by hand.

/** Inner SVG content for the `move` icon. Wrap with your own
 *  `<svg viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"
 *  stroke-linecap="round" stroke-linejoin="round" fill="none">` to
 *  control size and colour. */
export const move =
  '<path d="M12 2v20" /> <path d="m15 19-3 3-3-3" /> <path d="m19 9 3 3-3 3" /> <path d="M2 12h20" /> <path d="m5 9-3 3 3 3" /> <path d="m9 5 3-3 3 3" />';
