// play.ts — Mirrored from Lucide (https://lucide.dev), ISC licensed.
// Auto-generated by tools/build-icons.ts — do not edit by hand.

/** Inner SVG content for the `play` icon. Wrap with your own
 *  `<svg viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"
 *  stroke-linecap="round" stroke-linejoin="round" fill="none">` to
 *  control size and colour. */
export const play =
  '<path d="M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z" />';
