// rows-3.ts — Mirrored from Lucide (https://lucide.dev), ISC licensed.
// Auto-generated by tools/build-icons.ts — do not edit by hand.

/** Inner SVG content for the `rows-3` icon. Wrap with your own
 *  `<svg viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"
 *  stroke-linecap="round" stroke-linejoin="round" fill="none">` to
 *  control size and colour. */
export const rows3 =
  '<rect width="18" height="18" x="3" y="3" rx="2" /> <path d="M21 9H3" /> <path d="M21 15H3" />';
