// search.ts — Mirrored from Lucide (https://lucide.dev), ISC licensed.
// Auto-generated by tools/build-icons.ts — do not edit by hand.

/** Inner SVG content for the `search` icon. Wrap with your own
 * `<svg viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"
 * stroke-linecap="round" stroke-linejoin="round" fill="none">` to
 * control size and colour. */
export const search = '<path d="m21 21-4.34-4.34" /> <circle cx="11" cy="11" r="8" />';
