// shell.ts — Mirrored from Lucide (https://lucide.dev), ISC licensed.
// Auto-generated by tools/build-icons.ts — do not edit by hand.

/** Inner SVG content for the `shell` icon. Wrap with your own
 *  `<svg viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"
 *  stroke-linecap="round" stroke-linejoin="round" fill="none">` to
 *  control size and colour. */
export const shell =
  '<path d="M14 11a2 2 0 1 1-4 0 4 4 0 0 1 8 0 6 6 0 0 1-12 0 8 8 0 0 1 16 0 10 10 0 1 1-20 0 11.93 11.93 0 0 1 2.42-7.22 2 2 0 1 1 3.16 2.44" />';
