// sun.ts — Mirrored from Lucide (https://lucide.dev), ISC licensed.
// Auto-generated by tools/build-icons.ts — do not edit by hand.

/** Inner SVG content for the `sun` icon. Wrap with your own
 * `<svg viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"
 * stroke-linecap="round" stroke-linejoin="round" fill="none">` to
 * control size and colour. */
export const sun =
  '<circle cx="12" cy="12" r="4" /> <path d="M12 2v2" /> <path d="M12 20v2" /> <path d="m4.93 4.93 1.41 1.41" /> <path d="m17.66 17.66 1.41 1.41" /> <path d="M2 12h2" /> <path d="M20 12h2" /> <path d="m6.34 17.66-1.41 1.41" /> <path d="m19.07 4.93-1.41 1.41" />';
