// zap.ts — Mirrored from Lucide (https://lucide.dev), ISC licensed.
// Auto-generated by tools/build-icons.ts — do not edit by hand.

/** Inner SVG content for the `zap` icon. Wrap with your own
 *  `<svg viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"
 *  stroke-linecap="round" stroke-linejoin="round" fill="none">` to
 *  control size and colour. */
export const zap =
  '<path d="M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z" />';
