// build-icons.ts — Mirror specific Lucide icons into src/icons/.
//
// Reads SVGs from `lucide-static`'s installed `icons/<name>.svg`
// files, strips the outer <svg> wrapper (so consumers control sizing
// and stroke via their own <svg>), and writes ESM modules under
// `src/icons/`. Only the icons listed in ICONS_TO_MIRROR are emitted;
// growing the list = re-running the script. Output is committed to
// the repo so `@hexpunk/core` doesn't carry `lucide-static` as a
// runtime dep — the package is a build-time-only source of truth.
//
// Run: `bun run icons`. Format is invoked at the end so the
// generated files pass `format:check` in CI.

import { Glob } from "bun";
import { readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { resolve } from "node:path";

/** Lucide icon names to mirror, kebab-case as on lucide.dev.
 *  Each entry produces `src/icons/<name>.ts`. */
const ICONS_TO_MIRROR = ["copy", "moon", "scan", "search", "sun"];

/** Local icon names — sourced from `tools/icons/<name>.svg` instead of
 *  Lucide. Used for brand icons (e.g. GitHub) that Lucide dropped in
 *  recent versions but the showcase still needs. Generated `.ts`
 *  files carry a different header comment to reflect their origin. */
const LOCAL_ICONS = ["github"];

const ROOT = resolve(import.meta.dir, "..");
const LUCIDE_DIR = resolve(ROOT, "node_modules/lucide-static/icons");
const LOCAL_DIR = resolve(ROOT, "tools/icons");
const OUT_DIR = resolve(ROOT, "src/icons");

await mkdir(OUT_DIR, { recursive: true });

/** Extract the path content from a Lucide SVG file — drops the
 *  `<!-- license -->`, the `<svg ...>` wrapper, and trims to single-
 *  line `<path .../>` elements for compact emit. */
function extractInner(svg: string): string {
  const openIdx = svg.indexOf("<svg");
  const openEnd = svg.indexOf(">", openIdx);
  const closeIdx = svg.lastIndexOf("</svg>");
  if (openIdx < 0 || openEnd < 0 || closeIdx < 0) {
    throw new Error("malformed SVG — could not locate <svg> wrapper");
  }
  return svg
    .slice(openEnd + 1, closeIdx)
    .replaceAll(/\s+/g, " ")
    .trim();
}

function toCamel(name: string): string {
  return name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

const ALL_ICONS = [...ICONS_TO_MIRROR, ...LOCAL_ICONS].sort();

const existing = await Array.fromAsync(new Glob("*.ts").scan(OUT_DIR));
for (const file of existing) {
  if (file === "index.ts") {
    continue;
  }
  const base = file.replace(/\.ts$/, "");
  if (!ALL_ICONS.includes(base)) {
    await rm(resolve(OUT_DIR, file));
  }
}

for (const iconName of ICONS_TO_MIRROR) {
  const src = resolve(LUCIDE_DIR, `${iconName}.svg`);
  const raw = await readFile(src, "utf8");
  const inner = extractInner(raw);
  const varName = toCamel(iconName);
  const out = `// ${iconName}.ts — Mirrored from Lucide (https://lucide.dev), ISC licensed.
// Auto-generated by tools/build-icons.ts — do not edit by hand.

/** Inner SVG content for the \`${iconName}\` icon. Wrap with your own
 *  \`<svg viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"
 *  stroke-linecap="round" stroke-linejoin="round" fill="none">\` to
 *  control size and colour. */
export const ${varName} = ${JSON.stringify(inner)};
`;
  await writeFile(resolve(OUT_DIR, `${iconName}.ts`), out);
}

for (const iconName of LOCAL_ICONS) {
  const src = resolve(LOCAL_DIR, `${iconName}.svg`);
  const raw = await readFile(src, "utf8");
  const inner = extractInner(raw);
  const varName = toCamel(iconName);
  const out = `// ${iconName}.ts — Sourced from tools/icons/${iconName}.svg.
// Auto-generated by tools/build-icons.ts — do not edit by hand.

/** Inner SVG content for the \`${iconName}\` icon. Wrap with your own
 *  \`<svg viewBox="0 0 24 24">\` to control size; this icon ships as
 *  a brand mark (filled shape) rather than a Lucide stroke icon, so
 *  it ignores the standard \`stroke-*\` props. */
export const ${varName} = ${JSON.stringify(inner)};
`;
  await writeFile(resolve(OUT_DIR, `${iconName}.ts`), out);
}

// Re-emit the barrel.
const barrel = `// src/icons/index.ts — Generated by tools/build-icons.ts.
${ALL_ICONS.map((n) => `export { ${toCamel(n)} } from "./${n}.js";`).join("\n")}
`;
await writeFile(resolve(OUT_DIR, "index.ts"), barrel);

// Self-format the generated output.
await Bun.$`oxfmt ${OUT_DIR}`.quiet();

console.log(
  `build-icons: ${ICONS_TO_MIRROR.length} Lucide icon(s), ${LOCAL_ICONS.length} local icon(s) → src/icons/`
);
